---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: hexo/source/_posts
  label: Post
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: hexo
  label: Hexo
  create: all
  match: "**/*"
upload_dir: hexo/source/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: ".vuepress/dist"
  output_directory: ".vuepress/dist"
