# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: akinbosoyezaimoglu.com
subtitle: Online home for the Akinbosoye Zaimoglu's
description: Personal website for Akinbosoye Zaimoglu Family.
author: Temitope
language: en
timezone: UTC
keywords: Akinbosoye Zaimoglu

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://t4top.github.io/playground_hexo/
root: /playground_hexo/
permalink: blogs/:year/:month/:day/:title/

# Directory
source_dir: source
public_dir: ../docs
tag_dir: tags
archive_dir: blogs
category_dir: categories
code_dir:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
post_asset_folder: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
theme: a2z

# Deployment
deploy:
  type:
  repo:

disqus_shortname: akinbosoyezaimoglu-com
google_analytics: UA-131136908-1
twitter:
github: t4top/akinbosoyezaimoglu.com
