backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "source/uploads"
public_folder: "/uploads"

collections:
  - name: "post"
    label: "Blog Post" 
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Updated Date", name: "updated", widget: "hidden", default: ""}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Categories", name: "categories", widget: "hidden", default: "Blog"}
      - {label: "Enable Comments", name: comments, widget: boolean, default: false}
      - {label: Layout, name: layout, widget: hidden, default: "post"}
      - {label: Author, name: author, widget: "select", options: ["Temi", "Ozlem", "Deniz"]}
      - {label: "Table Of Content", name: toc, widget: boolean, default: false}
      - {label: "Thumbnail", name: thumbnail, widget: image, required: false}
      - {label: "Header Image", name: coverimage, widget: image, required: false}
      - {label: "Short Summary", name: "description", widget: "text", required: false}
      - {label: Author Image, name: authorimage, widget: hidden, default: "", required: false}
      - {label: Sharing, name: share, widget: boolean, default: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "page"
    label: "Page" 
    folder: "source"
    create: true
    slug: "/{{slug}}/index.md"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Updated Date", name: "updated", widget: "hidden", default: ""}
      - {label: "Enable Comments", name: comments, widget: boolean, default: false}
      - {label: Layout, name: layout, widget: hidden, default: "page"}
      - {label: Author, name: author, widget: "select", options: ["Temi", "Ozlem", "Deniz"]}
      - {label: "Table Of Content", name: toc, widget: boolean, default: false}
      - {label: "Header Image", name: coverimage, widget: image, required: false}
      - {label: "Short Summary", name: "description", widget: "text", required: false}
      - {label: Author Image, name: authorimage, widget: hidden, default: "", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
